// ==UserScript==
// @name         Cowlevel Style
// @namespace    http://www.zhouyuxin.net/
// @version      1.7
// @description  CowLevel Steam Color Theme
// @author       Arcadia
// @match        https://*.cowlevel.net/*
// ==/UserScript==




// Color Palette by Paletton.com
// Palette URL:
// http://paletton.com/#uid=73B1q0kkDcj63jybndRts8ARM6w


// Primary color:

var MAIN_COLOR_0='26,44,64';
var MAIN_COLOR_1='84,92,102';
var MAIN_COLOR_2='48,60,72';
var MAIN_COLOR_3='7,25,45';
var MAIN_COLOR_4='1,16,34';

// Secondary color (1):

var SECOND_COLOR_0 = '70, 25, 62';
var SECOND_COLOR_1 = '112, 91,108';
var SECOND_COLOR_2 = '79, 51, 74';
var SECOND_COLOR_3 = '49,  4, 40';
var SECOND_COLOR_4 = '37,  0, 30';

// Secondary color (2):

var THIRD_COLOR_0 = '80, 94, 33';
var THIRD_COLOR_1 = '142,149,121';
var THIRD_COLOR_2 = '97,105, 68';
var THIRD_COLOR_3 = '52, 65,  5';
var THIRD_COLOR_4 = '38, 50,  0';

// Complement color:

var COM_COLOR_0 = '98, 73, 35';
var COM_COLOR_1 = '156,144,126';
var COM_COLOR_2 = '110, 95, 71';
var COM_COLOR_3 = '68, 44,  5';
var COM_COLOR_4 = '52, 31,  0';

// Generated by Paletton.com (c) 2002-2014


var MAIN_BG_COLOR=MAIN_COLOR_0;
var SECOND_BG_COLOR=MAIN_COLOR_3;
var LIGHT_BG_COLOR=MAIN_COLOR_2;
var RED_BG_COLOR=SECOND_COLOR_0;


function addGlobalStyle(css) {
    var style = document.createElement('style');
    //style.type = 'text/css';
    style.innerHTML = css;
    document.body.appendChild(style);
}

(function() {
    'use strict';
    // Your code here...

    var css_value=`
        /* header */
        #snow-target.header-nav {
            background: var(--second_bg_color)
        }
        .top-nav {
            background: var(--second_bg_color)
        }
        .bottom-nav {
            background: var(--second_bg_color)
        }
        nav.header-nav.clearfix {
            background: var(--second_bg_color)
        }

        /* body */
        div.wrap-outer {
            background: var(--main_bg_color)
        }
        article.main.wrap-outer {
            background: var(--main_bg_color)
        }
        article.main {
            background: var(--main_bg_color)
        }
        body {
            background: var(--main_bg_color)
        }
        .footer {
            background: var(--main_bg_color)
        }

        /* transparent_background*/
        .bg-gradient-2 {background: rgba("+MAIN_BG_COLOR+",0.95)}
        .bg-gradient{background: -webkit-gradient(linear, 0 24%, 0 60%, from(rgba("+MAIN_BG_COLOR+",.1)), to(rgba("+MAIN_BG_COLOR+",1)));
                     background: linear-gradient(-180deg, rgba("+MAIN_BG_COLOR+",.1) 24%, rgba("+MAIN_BG_COLOR+",1) 100%);
                     background: -moz-linear-gradient(top, rgba("+MAIN_BG_COLOR+".1),rgba("+MAIN_BG_COLOR+",1))}
        .bg-gradient-3{background: -webkit-gradient(linear, 0 24%, 0 60%, from(rgba("+MAIN_BG_COLOR+",.1)), to(rgba("+MAIN_BG_COLOR+",1)));
                     background: linear-gradient(-180deg, rgba("+MAIN_BG_COLOR+",.1) 24%, rgba("+MAIN_BG_COLOR+",1) 100%);
                     background: -moz-linear-gradient(top, rgba("+MAIN_BG_COLOR+".1),rgba("+MAIN_BG_COLOR+",1))}
        .tip-window {
            background: var(--main_bg_color)
        }


        .tip-window {background: rgb("+MAIN_BG_COLOR+")}
        /* game review editor */
        #layui-layer2 > div > section {
            background: var(--main_bg_color)
        }
        #layui-layer2 > div > section > div > div.edit-signplayed-content-box.clearfix {
            background: var(--second_bg_color)
        }
        #layui-layer2 > div > section > div > div.edit-signplayed-content-box.clearfix > div > div.fr-footer > span {
            background: var(--second_bg_color)
        }
        div.fr-toolbar.custom-theme.fr-ltr.fr-desktop.fr-top.fr-basic.fr-sticky.fr-sticky-off {
            background: var(--second_bg_color)
        }

        /* settings */
            div.setting-card {
            background: var(--second_bg_color)
        }
        /* invite */
        section.invite-header.flex-box {
            background: var(--second_bg_color)
        }
        section.vm-user-item-card {
            background: var(--second_bg_color)
        }
        section.vm-invitation-item.bg-img {
            background-image: url("http://www.mountnoon.com/assets/files/2017-03-22/04:07:240-ticket2x-solarized.png")
        }

        .open-layer {
            background: var(--second_bg_color)
        }
        .setting-list {
            background: var(--second_bg_color)
        }
        .feedback-layer {
            background: var(--main_bg_color)
        }
        .layui-layer-title {
            background: var(--main_bg_color)
        }
        .layer {
            background: var(--main_bg_color)
        }
        .single-post {
            background: var(--main_bg_color)
        }
        .comments.wrapper.fat-footer {
            background: var(--second_bg_color)
        }
        .comments {
            background: var(--main_bg_color)
        }
        .btn-card-border {
            background: var(--second_bg_color)
        }
        .notice-tip-window {
            background-color: var(--main_bg_color)
        }
        .notice-tab li.weidu {
            background-color: var(--main_bg_color)
        }
        .tip-tag {
            background: var(--second_bg_color)
        }
        div.tip-game {
            background: var(--second_bg_color)
        }
        .hot-box.cl-card {
            background: var(--second_bg_color)
        }
        .swiper-slide.cl-shadow.block {
            background: var(--second_bg_color)
        }
        .wanguo-swiper.shouchang-swiper.swiper-slide {
            background: var(--second_bg_color)
        }
        .vm-feed-card-article {
            background: var(--second_bg_color)
        }
        .vm-feed-card-answer {
            background: var(--second_bg_color)
        }
        .vm-feed-card-question {
            background: var(--second_bg_color)
        }
        .vm-feed-card-review {
            background: var(--second_bg_color)
        }
        .vm-feed-card-game {
            background: var(--second_bg_color)
        }
        .vm-feed-card-played {
            background: var(--second_bg_color)
        }
        .vm-feed-card-answer-comment {
            background: var(--second_bg_color)
        }
        div.vm-personal-card > .clearfix {
            background: var(--light_bg_color)
        }
        .vm-style-double-bevel {
            background: var(--light_bg_color);
            padding-top: 3px
        }
        .vm-layer-more-user {
            background: var(--main_bg_color)
        }
        section.vm-avatar.flex-box {
            background: var(--second_bg_color)
        }
        .left-bevel {
            display: none
        }
        .right-bevel {
            display: none
        }
        .wangEditor-container {
            background: var(--second_bg_color)
        }
        .wangEditor-menu-container {
            background: var(--second_bg_color)
        }
        .cl-card {
            background: var(--second_bg_color)
        }
        .vm-element-item {
            background: var(--second_bg_color)
        }
        .vm-element-item.white.on {
            background: var(--red_bg_color)
        }
        .vm-element-game-item {
            background: var(--second_bg_color)
        }
        .vm-element-header {
            background: var(--second_bg_color)
        }
        div.desc.sticky-box > .flex-box.flex-align-items-center.footer-info-box {
            background: var(--second_bg_color)
        }
        div.tag-box.white {
            background: var(--second_bg_color)
        }
        div.tag-box.white.on {
            background: var(--red_bg_color)
        }
        div.tag-box.white.hover {
            background: var(--light_bg_color)
        }
        .add-question-box {
            background: var(--second_bg_color)
        }
    `;
    addGlobalStyle(css_value);

    //change in-line style
    try {
        document.getElementsByClassName("bg-gradient-2")[0].style.background="rgba("+MAIN_BG_COLOR+",0.9)";
    }
    catch (err) {
    }
})();
